# Generated by Django 6.0.4 on 2026-04-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blog_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedata',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='home/'),
        ),
    ]
