# Generated by Django 6.0.4 on 2026-04-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_homedata_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
            ],
        ),
    ]
