# Generated by Django 6.0.4 on 2026-04-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=100)),
                ('project_complete', models.CharField(max_length=50)),
                ('happy_clients', models.CharField(max_length=1000)),
            ],
        ),
    ]
