# Generated by Django 6.0.4 on 2026-04-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_informationsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_under_const', models.BooleanField(default=False)),
                ('uc_note', models.TextField(blank=True, help_text='Note for under construction..', null=True)),
                ('uc_duration', models.DateTimeField(blank=True, help_text='End duration for under construction..', null=True)),
                ('uc_update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
